### ISSUE TITLE
comments ≠ code ?

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/anvil#1]
In .wslconfig:
```
# Limits VM memory to use no more than 4 GB, this can be set as whole numbers using GB or MB
memory=16GB 

# Sets the VM to use two virtual processors
processors=8
```
the comments don't appear to match the code -- unless I'm not understanding something.

**Comment by bobh0303** [comment]
Is the comment about virtual processors correct?

**Comment by n7s** [comment]
Thanks for pointing out the  unclear comments, I didn't adjust it when I tried multiple values. It should now be adjusted. With a link to the upstream doc.
