### ISSUE TITLE
backup-wsl-repositories.bat suggestions

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/anvil#2]
Personally I think the script is too noisy. 

Examples:
- With just 9 font repos it produces over 1000 lines of output to the terminal whether or not it actually has to back up any files. And the lines it outputs are just the names of directories, so we can't actually see what files were backed up.
- If I remove a repo from `repos/wstechfonts`, then on the next backup every file in the previously backed up copy of that repo generates an `*EXTRA File ...` line to the screen as it is being deleted, and [apparently](https://superuser.com/questions/511702/how-do-i-hide-extra-file-and-100-lines-from-robocopy-output) there is no switch to turn this off.

My proposal would be to first remove the /NFL option (so we can see what files were actually backed up if we need to) and then write everything to a log file that gets overwritten on each use. e.g.:
```
set LOG="%USERPROFILE%\WSL-repositories-backup.log"
...
robocopy W:\home\%WSL-UBUNTU-USER%\repos\wstechfonts  %BACKUPDIR%  /MIR /FFT /Z /ETA /NP /LOG:%LOG%
```

NB: The `/NP` option quiets an extra line for every file saying the percentage of the file copied, which seems to always be 100%.

And, again this is my personal taste, I think there is no reason for the `PAUSE` statement at the end. If someone wants to run this by double-clicking something (rather than from an existing cmd prompt) they can set up a shortcut to `cmd /K path\backup-wsl-repositories.bat` in order to be able to read the output.

**Comment by n7s** [comment]
OK, the batch file was tweaked to be quieter and potentially more user friendly. Power users can adjust what they want or have another backup approach entirely.
