### ISSUE TITLE
Unknown key in .wslconfig

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/anvil#3]
In `.wslconfig` the following:

https://github.com/silnrsi/anvil/blob/e9e86f09fd21d9ab47140ffafb3992f302d9d618/.wslconfig#L19-L20

generates a Warning during WSL startup:
```
Unknown key 'wsl2.pageReporting' in C:\Users\bobh\.wslconfig:20
```
On my machine this warning is visible using Event Viewer

**Comment by nrsiward** [comment]
FYI:

`https://github.com/microsoft/WSL/issues/9899`

`https://www.tenforums.com/windows-10-news/203884-windows-subsystem-linux-wsl-1-1-7-released.html`

Perhaps this key is no longer supported but yet the official documentation has not been updated?
